from enum import Enum, auto

class TileType(Enum):

    WALL = auto()
    WALL_ONW = auto()
    WALL_ONE = auto()
    WALL_OSE = auto()
    WALL_OSW = auto()
    WALL_ON = auto()
    WALL_OS = auto()
    WALL_OE = auto()
    WALL_OW = auto()
    WALL_INW = auto()
    WALL_INE = auto()
    WALL_ISE = auto()
    WALL_ISW = auto()
    WALL_IN = auto()
    WALL_IS = auto()
    WALL_IE = auto()
    WALL_IW = auto()
    EMPTY = auto()
    PELLET = auto()
    POWER_PELLET = auto()
    DOOR = auto()
    TUNNEL = auto()
